/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find the total customers by countries
select country, count(customer_key) as total_customers from gold.dim_customers
group by country
order by total_customers desc

-- Find the total cutomers by gender
select gender, count(customer_key) from gold.dim_customers
group by gender

-- Find the total products by category
select category, count(product_key) from gold.dim_products
group by category

-- What is the average costs in each category?
select category, avg(product_cost) from gold.dim_products
group by category

-- What is the total revenue generated for each category?
select category, sum(sales_amount) as toal_revenue 
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by category

-- Find total revenue generated by each customer
select f.customer_key, firstname, lastname, sum(sales_amount) as total_revenue 
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by f.customer_key, firstname, lastname
order by total_revenue desc

-- What is the distribution of sold items(which means total quantity of items) across countries?
select country, sum(quantity) as total_sold_items 
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by country
order by total_sold_items desc
